[tool.poetry]
name = "cricket"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
polars = "^0.20.22"
numpy = "^1.26.4"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
isort = "^5.12.0"
pytest = "^7.4.2"
ruff = "^0.1.11"
matplotlib = "^3.8.4"
seaborn = "^0.13.2"
pyarrow = "^16.0.0"

[tool.ruff]
line-length=79

[tool.ruff.lint]
select = ["F", "I"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
