name: linting_formatting_testing

on: [push]

jobs:
  run_:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run linter
        run: uv run ruff check .

      - name: Run formatter
        run: uv run poe format-check

      - name: Run type checker
        run: uv run ty check

      - name: Run tests
        run: uv run pytest